"""Report rendering helpers for market document_full PostgreSQL gates."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[3]
EMBEDDED_LOCAL_PATH_RE = re.compile(r"(?:/(?:home|Users|tmp)/[^\s`\"'|,;]+|[A-Za-z]:\\+Users\\+[^\s`\"'|,;]+)")


def _redact_report_paths(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _redact_report_paths(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_redact_report_paths(item) for item in value]
    if not isinstance(value, str):
        return value
    path = Path(value)
    if path.is_absolute():
        try:
            return path.resolve().relative_to(REPO_ROOT.resolve()).as_posix()
        except ValueError:
            return "[external]"
    return EMBEDDED_LOCAL_PATH_RE.sub("[local-path]", value)


def write_report(summary: dict[str, Any], output_path: Path | None, markdown_path: Path | None) -> None:
    safe_summary = _redact_report_paths(summary)
    if output_path is not None:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(json.dumps(safe_summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if markdown_path is not None:
        markdown_path.parent.mkdir(parents=True, exist_ok=True)
        markdown_path.write_text(render_markdown_report(safe_summary), encoding="utf-8")


def render_markdown_report(summary: dict[str, Any]) -> str:
    contract_status = "PASS" if summary.get("passed") else "FAIL"
    acceptance_status = "PASS" if summary.get("acceptance_passed") else "PENDING"
    summary_payload = summary.get("summary", {})
    lines = [
        "# Market Document Full PostgreSQL Backtest",
        "",
        f"Contract status: **{contract_status}**",
        f"Acceptance status: **{acceptance_status}**",
        "",
        "This report is generated by `db/imports/backtests/market_document_full_postgres_backtest.py`.",
        "Current mode validates the `document_full.json` contract fixtures, fixed fixture fact-lookups, and real-sample manifest; optional `--db --import-before-db-check --idempotency --production-sample-db --production-agent-query` performs PostgreSQL table-family/table count checks, required-evidence checks, row-count stability checks, real-sample DB idempotency checks, and Agent-view query checks.",
        "",
        "## Summary",
        "",
        f"- Cases: {summary.get('passed_count')}/{summary.get('case_count')} passed",
        f"- Assertions: {summary_payload.get('assertion_count', 0)}",
        f"- Common-core assertions: {summary_payload.get('common_core_assertion_count', 0)}",
        f"- Required-evidence assertions: {summary_payload.get('required_evidence_assertion_count', 0)}",
        f"- Evidence coverage ratio: {summary_payload.get('evidence_coverage_ratio', 0):.3f}",
        f"- Unit checks: {summary_payload.get('unit_checked_assertion_count', 0)}",
        f"- Currency checks: {summary_payload.get('currency_checked_assertion_count', 0)}",
        f"- Unit/currency explainability ratio: {summary_payload.get('unit_currency_explainability_ratio', 0):.3f}",
        f"- PostgreSQL existing-row check verified: {summary_payload.get('postgres_existing_row_check_verified')}",
        f"- Fixture PostgreSQL policy: {summary_payload.get('fixture_postgres_policy')}",
        f"- Fixture PostgreSQL access executed: {summary_payload.get('fixture_postgres_access_executed')}",
        f"- Fixture PostgreSQL import executed: {summary_payload.get('fixture_postgres_import_executed')}",
        f"- PostgreSQL roundtrip verified: {summary_payload.get('postgres_roundtrip_verified')}",
        f"- PostgreSQL import executed: {summary_payload.get('postgres_import_executed')}",
        f"- PostgreSQL idempotency verified: {summary_payload.get('postgres_idempotency_verified')}",
        f"- PostgreSQL roundtrip cases: {summary_payload.get('postgres_roundtrip_passed_count', 0)}/{summary_payload.get('postgres_roundtrip_case_count', 0)}",
        f"- PostgreSQL family count checks: {summary_payload.get('postgres_family_count_checked_count', 0)}",
        f"- PostgreSQL table count checks: {summary_payload.get('postgres_table_count_checked_count', 0)}",
        f"- PostgreSQL scope issues: {summary_payload.get('postgres_scope_issue_count', 0)}",
        f"- PostgreSQL required-evidence checks: {summary_payload.get('postgres_required_evidence_passed_count', 0)}/{summary_payload.get('postgres_required_evidence_checked_count', 0)}",
        f"- Real sample minimum met: {summary_payload.get('real_sample_minimum_met')}",
        f"- Real sample manifest: {summary_payload.get('production_sample_manifest_path')}",
        f"- Real sample files required: {summary_payload.get('production_sample_require_existing')}",
        f"- Real sample manifest counts: `{json.dumps(summary_payload.get('production_sample_manifest_counts') or {}, ensure_ascii=False, sort_keys=True)}`",
        f"- Real sample existing counts: `{json.dumps(summary_payload.get('production_sample_existing_counts') or {}, ensure_ascii=False, sort_keys=True)}`",
        f"- Real sample DB executed: {summary_payload.get('production_sample_db_executed')}",
        f"- Real sample DB verified: {summary_payload.get('production_sample_db_verified')}",
        f"- Real sample DB idempotency verified: {summary_payload.get('production_sample_idempotency_verified')}",
        f"- Real sample DB cases: {summary_payload.get('production_sample_db_passed_count', 0)}/{summary_payload.get('production_sample_db_case_count', 0)}",
        f"- Real sample DB scope issues: {summary_payload.get('production_sample_db_scope_issue_count', 0)}",
        f"- Real sample DB coexistence verified: {summary_payload.get('production_sample_db_coexistence_verified')}",
        f"- Real sample DB coexistence markets: {summary_payload.get('production_sample_db_coexistence_passed_count', 0)}/{summary_payload.get('production_sample_db_coexistence_market_count', 0)}",
        f"- Fixture Agent fact lookup verified: {summary_payload.get('agent_query_verified')}",
        f"- Fixture Agent fact lookup cases: {summary_payload.get('agent_query_passed_count', 0)}/{summary_payload.get('agent_query_case_count', 0)}",
        f"- Production Agent query executed: {summary_payload.get('production_agent_query_executed')}",
        f"- Production Agent query verified: {summary_payload.get('production_agent_query_verified')}",
        f"- Production Agent query cases: {summary_payload.get('production_agent_query_passed_count', 0)}/{summary_payload.get('production_agent_query_case_count', 0)}",
        f"- Real sample Agent view verified: {summary_payload.get('production_sample_agent_view_verified')}",
        f"- Real sample Agent view cases: {summary_payload.get('production_sample_agent_view_passed_count', 0)}/{summary_payload.get('production_sample_agent_view_case_count', 0)}",
        f"- Wiki/PostgreSQL query parity verified: {summary_payload.get('wiki_postgres_query_parity_verified')}",
        f"- Wiki/PostgreSQL query parity cases: {summary_payload.get('wiki_postgres_query_parity_passed_count', 0)}/{summary_payload.get('wiki_postgres_query_parity_case_count', 0)}",
        f"- Real sample Wiki/PostgreSQL parity cases: {summary_payload.get('production_sample_wiki_postgres_query_parity_passed_count', 0)}/{summary_payload.get('production_sample_wiki_postgres_query_parity_case_count', 0)}",
        f"- Wiki/PostgreSQL parity warnings: {summary_payload.get('wiki_postgres_query_parity_warning_count', 0)}",
        f"- Real sample Wiki/PostgreSQL parity warnings: {summary_payload.get('production_sample_wiki_postgres_query_parity_warning_count', 0)}",
        f"- Wiki/PostgreSQL parity diff codes: `{json.dumps(summary_payload.get('wiki_postgres_query_parity_diff_code_counts') or {}, ensure_ascii=False, sort_keys=True)}`",
        f"- Real sample Wiki/PostgreSQL parity diff codes: `{json.dumps(summary_payload.get('production_sample_wiki_postgres_query_parity_diff_code_counts') or {}, ensure_ascii=False, sort_keys=True)}`",
        "",
        "## Acceptance Requirements",
        "",
        "| Requirement | Status |",
        "| --- | --- |",
    ]
    for name, passed in (summary.get("acceptance_requirements") or {}).items():
        lines.append(f"| {name} | {'PASS' if passed else 'PENDING'} |")
    lines.extend([
        "",
        "## Markets",
        "",
        "| Market | Cases |",
        "| --- | ---: |",
    ])
    for market, count in sorted((summary.get("market_counts") or {}).items()):
        lines.append(f"| {market} | {count} |")
    lines.extend([
        "",
        "## Cases",
        "",
        "| Case | Market | Status | Facts |",
        "| --- | --- | --- | ---: |",
    ])
    for result in summary.get("results") or []:
        case_status = "PASS" if result.get("passed") else "FAIL"
        lines.append(f"| {result.get('case_id')} | {result.get('market')} | {case_status} | {result.get('fact_count')} |")
        for error in result.get("errors") or []:
            lines.append(f"| {result.get('case_id')} error | {result.get('market')} | `{error}` |  |")
    lines.extend([
        "",
        "## Fixture Agent Fact Lookup",
        "",
        "| Case | Market | Status | Checks |",
        "| --- | --- | --- | ---: |",
    ])
    for result in summary.get("agent_results") or []:
        case_status = "PASS" if result.get("passed") else "FAIL"
        lines.append(f"| {result.get('case_id')} | {result.get('market')} | {case_status} | {result.get('checked', 0)} |")
        for error in result.get("errors") or []:
            lines.append(f"| {result.get('case_id')} error | {result.get('market')} | `{error}` |  |")
    if summary.get("db_results"):
        lines.extend([
            "",
            "## PostgreSQL Roundtrip",
            "",
            "| Case | Market | Status | Counts |",
            "| --- | --- | --- | --- |",
        ])
        for result in summary.get("db_results") or []:
            if result.get("skipped"):
                status = "SKIP"
            else:
                status = "PASS" if result.get("passed") else "FAIL"
            counts = json.dumps(result.get("counts") or {}, ensure_ascii=False, sort_keys=True)
            lines.append(f"| {result.get('case_id')} | {result.get('market')} | {status} | `{counts}` |")
            for error in result.get("errors") or []:
                lines.append(f"| {result.get('case_id')} error | {result.get('market')} | `{error}` |  |")
    if summary.get("production_sample_db_results"):
        lines.extend([
            "",
            "## Real Sample PostgreSQL",
            "",
            "| Case | Market | Status | Counts |",
            "| --- | --- | --- | --- |",
        ])
        for result in summary.get("production_sample_db_results") or []:
            status = "PASS" if result.get("passed") else "FAIL"
            counts = json.dumps(result.get("counts") or {}, ensure_ascii=False, sort_keys=True)
            lines.append(f"| {result.get('case_id')} | {result.get('market')} | {status} | `{counts}` |")
            for error in result.get("errors") or []:
                lines.append(f"| {result.get('case_id')} error | {result.get('market')} | `{error}` |  |")
    if summary.get("production_sample_db_coexistence_results"):
        lines.extend([
            "",
            "## Real Sample PostgreSQL Coexistence",
            "",
            "| Market | Status | Parse Runs |",
            "| --- | --- | --- |",
        ])
        for result in summary.get("production_sample_db_coexistence_results") or []:
            status = "PASS" if result.get("passed") else "FAIL"
            observed = json.dumps(result.get("observed_parse_run_ids") or [], ensure_ascii=False)
            lines.append(f"| {result.get('market')} | {status} | `{observed}` |")
            for error in result.get("errors") or []:
                lines.append(f"| {result.get('market')} error |  | `{error}` |")
    if summary.get("production_agent_results"):
        lines.extend([
            "",
            "## Production Agent View Query",
            "",
            "| Case | Market | Mode | Status | Checks/Rows |",
            "| --- | --- | --- | --- | ---: |",
        ])
        for result in summary.get("production_agent_results") or []:
            if result.get("skipped"):
                status = "SKIP"
            else:
                status = "PASS" if result.get("passed") else "FAIL"
            checks_or_rows = result.get("checked", result.get("row_count", 0))
            lines.append(f"| {result.get('case_id')} | {result.get('market')} | {result.get('mode')} | {status} | {checks_or_rows} |")
            for error in result.get("errors") or []:
                lines.append(f"| {result.get('case_id')} error | {result.get('market')} | {result.get('mode')} | `{error}` |  |")
    parity_results = (summary.get("wiki_postgres_parity_results") or []) + (
        summary.get("production_sample_wiki_postgres_parity_results") or []
    )
    if parity_results:
        lines.extend([
            "",
            "## Wiki PostgreSQL Query Parity",
            "",
            "| Case | Market | Status | Checks | Codes |",
            "| --- | --- | --- | ---: | --- |",
        ])
        for result in parity_results:
            if result.get("skipped"):
                status = "SKIP"
            else:
                status = "PASS" if result.get("passed") else "FAIL"
            codes = json.dumps(result.get("diff_code_counts") or {}, ensure_ascii=False, sort_keys=True)
            lines.append(f"| {result.get('case_id')} | {result.get('market')} | {status} | {result.get('checked', 0)} | `{codes}` |")
            for error in result.get("errors") or []:
                lines.append(f"| {result.get('case_id')} error | {result.get('market')} | `{error}` |  |  |")
            for warning in result.get("warnings") or []:
                lines.append(f"| {result.get('case_id')} warning | {result.get('market')} | `{warning}` |  |  |")
    remaining = [
        name
        for name, passed in (summary.get("acceptance_requirements") or {}).items()
        if not passed
    ]
    lines.extend([
        "",
        "## Remaining Production Gates",
        "",
    ])
    if remaining:
        lines.extend(f"- {name}" for name in remaining)
    else:
        lines.append("- None")
    return "\n".join(lines)


__all__ = ["render_markdown_report", "write_report"]
