from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
from urllib.parse import urlparse
import re

import httpx

from report_finder_service.core.config import settings
from report_finder_service.models.schemas import (
    DirectReportDownloadResponse,
    DownloadedReportFile,
    Market,
    ReportCandidate,
    ReportType,
)


REPORT_FINDER_FILE_NAME_RE = re.compile(
    r"^(?P<company_name>.+?)_"
    r"(?P<market>CN|HK|US)_"
    r"(?P<ticker>[^_]+)_"
    r"(?P<report_end>\d{4}-\d{2}-\d{2})_"
    r"(?P<report_type>[^_]+)_"
    r"(?P<published_at>\d{4}-\d{2}-\d{2})_"
    r"(?P<source_id>.+)_"
    r"(?P<url_hash>[0-9a-fA-F]{8})$",
)


def parse_report_finder_file_name(file_name: str) -> dict[str, str]:
    """Parse files generated by ReportDownloader._build_file_name()."""
    stem = Path(str(file_name or "")).name
    suffix = Path(stem).suffix.lower().lstrip(".")
    if suffix:
        stem = stem[: -(len(suffix) + 1)]
    match = REPORT_FINDER_FILE_NAME_RE.match(stem)
    if not match:
        return {}
    parsed = match.groupdict()
    if suffix:
        parsed["file_format"] = suffix
    return parsed


class ReportDownloader:
    REPORT_TYPE_LABELS = {
        ReportType.annual: "年报",
        ReportType.semiannual: "半年报",
        ReportType.q1: "一季报",
        ReportType.q3: "三季报",
        ReportType.form_10k: "10-K",
        ReportType.form_20f: "20-F",
        ReportType.form_10q: "10-Q",
        ReportType.form_6k: "6-K",
        ReportType.earnings: "业绩公告",
    }

    def download(
        self,
        candidate: ReportCandidate,
        sub_dir: str | None = None,
    ) -> DownloadedReportFile:
        download_dir = Path(settings.download_dir).expanduser()
        # 按报告类型分二级目录：年报 / 财报
        type_folder = "年报" if candidate.report_type == ReportType.annual else "财报"
        if sub_dir:
            download_dir = download_dir / sub_dir / type_folder
        else:
            download_dir = download_dir / type_folder
        download_dir.mkdir(parents=True, exist_ok=True)
        index_path = download_dir / settings.download_index_file
        index = self._load_index(index_path)

        file_name = self._build_file_name(candidate)
        file_path = download_dir / file_name
        content_type: str | None = None

        if not settings.download_overwrite:
            cached = self._lookup_cached(index, candidate)
            if cached is not None:
                cached = self._migrate_cached_name(index_path, index, candidate, cached, file_path)
                return cached

        if settings.download_overwrite or not file_path.exists():
            with self._client(candidate.source_id) as client:
                response = client.get(candidate.document_url)
                response.raise_for_status()
                content_type = response.headers.get("content-type")
                content = response.content
        else:
            content = file_path.read_bytes()

        content_sha256 = self._sha256_bytes(content)
        if not settings.download_overwrite:
            deduped = self._lookup_by_digest(index, content_sha256)
            if deduped is not None:
                self._register_alias(index, candidate, deduped["saved_path"], deduped.get("content_type"), content_sha256)
                self._save_index(index_path, index)
                existing_path = Path(deduped["saved_path"])
                return DownloadedReportFile(
                    file_name=existing_path.name,
                    saved_path=str(existing_path.resolve()),
                    size_bytes=existing_path.stat().st_size,
                    content_type=deduped.get("content_type") or self._content_type_from_suffix(existing_path.suffix),
                    downloaded_at=datetime.now(timezone.utc),
                    cache_hit=False,
                    deduplicated=True,
                    content_sha256=content_sha256,
                )

        file_path.write_bytes(content)
        if content_type is None:
            content_type = self._content_type_from_suffix(file_path.suffix)
        self._register_alias(index, candidate, str(file_path.resolve()), content_type, content_sha256)
        self._save_index(index_path, index)

        return DownloadedReportFile(
            file_name=file_path.name,
            saved_path=str(file_path.resolve()),
            size_bytes=file_path.stat().st_size,
            content_type=content_type,
            downloaded_at=datetime.now(timezone.utc),
            cache_hit=False,
            deduplicated=False,
            content_sha256=content_sha256,
        )

    def _migrate_cached_name(
        self,
        index_path: Path,
        index: dict,
        candidate: ReportCandidate,
        cached: DownloadedReportFile,
        target_path: Path,
    ) -> DownloadedReportFile:
        current_path = Path(cached.saved_path)
        if current_path.resolve() == target_path.resolve():
            return cached
        migrated_path = self._migrate_path(current_path, target_path)
        self._register_alias(index, candidate, str(migrated_path.resolve()), cached.content_type, cached.content_sha256)
        self._save_index(index_path, index)
        return DownloadedReportFile(
            file_name=migrated_path.name,
            saved_path=str(migrated_path.resolve()),
            size_bytes=migrated_path.stat().st_size,
            content_type=cached.content_type or self._content_type_from_suffix(migrated_path.suffix),
            downloaded_at=datetime.now(timezone.utc),
            cache_hit=True,
            deduplicated=current_path.resolve() != migrated_path.resolve(),
            content_sha256=cached.content_sha256,
        )

    @staticmethod
    def _migrate_path(current_path: Path, target_path: Path) -> Path:
        if current_path.resolve() == target_path.resolve():
            return current_path
        target_path.parent.mkdir(parents=True, exist_ok=True)
        if target_path.exists():
            return target_path
        current_path.rename(target_path)
        return target_path

    def download_direct(
        self,
        *,
        company_name: str,
        document_url: str,
        landing_url: str | None,
        source_name: str,
        report_type: ReportType,
        report_end,
        published_at,
    ) -> DirectReportDownloadResponse:
        source_domain = urlparse(document_url).netloc or "manual"
        candidate = ReportCandidate(
            source_id="manual_official",
            source_name=source_name,
            source_domain=source_domain,
            company_name=company_name,
            ticker="manual",
            market=Market.cn,
            report_type=report_type,
            title=f"{company_name} {report_type.value}",
            report_end=report_end,
            published_at=published_at,
            document_url=document_url,
            landing_url=landing_url or document_url,
            file_format=Path(urlparse(document_url).path).suffix.lstrip(".") or "pdf",
        )
        downloaded_file = self.download(candidate)
        return DirectReportDownloadResponse(
            company_name=company_name,
            source_name=source_name,
            source_domain=source_domain,
            document_url=document_url,
            landing_url=landing_url,
            report_type=report_type,
            report_end=report_end,
            published_at=published_at,
            downloaded_file=downloaded_file,
        )

    @staticmethod
    def _sha256_bytes(content: bytes) -> str:
        return hashlib.sha256(content).hexdigest()

    def _load_index(self, index_path: Path) -> dict:
        if not index_path.exists():
            return {
                "by_document_url": {},
                "by_landing_url": {},
                "by_content_sha256": {},
            }
        try:
            return json.loads(index_path.read_text(encoding="utf-8"))
        except Exception:
            return {
                "by_document_url": {},
                "by_landing_url": {},
                "by_content_sha256": {},
            }

    def _save_index(self, index_path: Path, index: dict) -> None:
        index_path.write_text(json.dumps(index, ensure_ascii=False, indent=2), encoding="utf-8")

    def _lookup_cached(self, index: dict, candidate: ReportCandidate) -> DownloadedReportFile | None:
        for key, lookup in [
            (candidate.document_url, index.get("by_document_url", {})),
            (candidate.landing_url, index.get("by_landing_url", {})),
        ]:
            if not key:
                continue
            entry = lookup.get(key)
            if not entry:
                continue
            file_path = Path(entry["saved_path"])
            if not file_path.exists():
                continue
            return DownloadedReportFile(
                file_name=file_path.name,
                saved_path=str(file_path.resolve()),
                size_bytes=file_path.stat().st_size,
                content_type=entry.get("content_type") or self._content_type_from_suffix(file_path.suffix),
                downloaded_at=datetime.now(timezone.utc),
                cache_hit=True,
                deduplicated=file_path.name != self._build_file_name(candidate),
                content_sha256=entry.get("content_sha256"),
            )
        if candidate.document_url:
            type_folder = "年报" if candidate.report_type == ReportType.annual else "财报"
            file_path = Path(settings.download_dir).expanduser() / type_folder / self._build_file_name(candidate)
            if file_path.exists():
                return DownloadedReportFile(
                    file_name=file_path.name,
                    saved_path=str(file_path.resolve()),
                    size_bytes=file_path.stat().st_size,
                    content_type=self._content_type_from_suffix(file_path.suffix),
                    downloaded_at=datetime.now(timezone.utc),
                    cache_hit=True,
                    deduplicated=False,
                    content_sha256=None,
                )
        return None

    @staticmethod
    def _lookup_by_digest(index: dict, content_sha256: str) -> dict | None:
        entry = index.get("by_content_sha256", {}).get(content_sha256)
        if not entry:
            return None
        file_path = Path(entry["saved_path"])
        if not file_path.exists():
            return None
        return entry

    def _register_alias(
        self,
        index: dict,
        candidate: ReportCandidate,
        saved_path: str,
        content_type: str | None,
        content_sha256: str | None,
    ) -> None:
        entry = {
            "saved_path": saved_path,
            "file_name": Path(saved_path).name,
            "content_type": content_type,
            "content_sha256": content_sha256,
            "source_id": candidate.source_id,
            "ticker": candidate.ticker,
            "report_end": candidate.report_end.isoformat(),
            "report_type": candidate.report_type.value,
        }
        index.setdefault("by_document_url", {})[candidate.document_url] = entry
        if candidate.landing_url:
            index.setdefault("by_landing_url", {})[candidate.landing_url] = entry
        if content_sha256:
            index.setdefault("by_content_sha256", {})[content_sha256] = entry

    def _client(self, source_id: str) -> httpx.Client:
        return httpx.Client(
            timeout=settings.http_timeout_seconds,
            headers=self._headers_for_source(source_id),
            follow_redirects=True,
        )

    def _headers_for_source(self, source_id: str) -> dict[str, str]:
        headers = {"User-Agent": settings.sec_user_agent}
        if source_id == "cninfo":
            headers["Referer"] = (
                "https://www.cninfo.com.cn/new/commonUrl/pageOfSearch?url=disclosure/list/search"
            )
        if source_id == "sec":
            headers["Accept-Encoding"] = "gzip, deflate"
        return headers

    def _build_file_name(self, candidate: ReportCandidate) -> str:
        suffix = self._file_suffix(candidate)
        report_type = self.REPORT_TYPE_LABELS.get(candidate.report_type, candidate.report_type.value)
        url_hash = hashlib.sha256(candidate.document_url.encode("utf-8")).hexdigest()[:8]
        parts = [
            candidate.company_name,
            f"{candidate.market.value}_{candidate.ticker}",
            candidate.report_end.isoformat(),
            report_type,
            candidate.published_at.isoformat(),
            candidate.source_id,
            url_hash,
        ]
        return "_".join(self._safe_filename_part(part) for part in parts) + suffix

    @staticmethod
    def _safe_filename_part(value: object) -> str:
        text = str(value or "").strip()
        text = re.sub(r'[\\/:*?"<>|\s]+', "-", text)
        text = re.sub(r"-{2,}", "-", text).strip(".-_")
        return text or "unknown"

    @staticmethod
    def _file_suffix(candidate: ReportCandidate) -> str:
        declared = candidate.file_format.strip().lower().lstrip(".")
        if declared:
            return f".{declared}"

        path = urlparse(candidate.document_url).path
        suffix = Path(path).suffix.lower()
        if suffix:
            return suffix
        return ".bin"

    @staticmethod
    def _content_type_from_suffix(suffix: str) -> str | None:
        mapping = {
            ".pdf": "application/pdf",
            ".htm": "text/html",
            ".html": "text/html",
            ".txt": "text/plain",
            ".xml": "application/xml",
        }
        return mapping.get(suffix.lower())
