version: 1
filesystem_policy:
  include_workdir: false
  read_only:
    - /dev/urandom
    - /etc
    - /home/sandbox
    - /lib
    - /opt/hermes-agent
    - /opt/siq-poc
    - /proc
    - /usr
    - /var/log
  read_write:
    - /dev/null
    - /home/sandbox/.hermes
    - /sandbox
    - /tmp
    - /workspace
landlock:
  compatibility: hard_requirement
process:
  run_as_group: sandbox
  run_as_user: sandbox
network_policies: {}
