#!/usr/bin/env python3
"""Upgrade an existing rich SIQ markdown report into v1.1 structure.

This keeps the richer legacy analysis body and citations, then remaps it into
the fixed 14-module SIQ v1.1 template. It is intended as a quality repair
step for reports that were generated by the checkpoint fallback renderer.
"""

from __future__ import annotations

import argparse
import html
import json
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Any

PUBLIC_ORIGIN = os.environ.get("SIQ_PUBLIC_ORIGIN", "").rstrip("/")


def public_api_url(path: str) -> str:
    if path.startswith(("http://", "https://")):
        return path
    if path.startswith("/"):
        return f"{PUBLIC_ORIGIN}{path}"
    return path


SECTION_MAP = [
    ("executive_summary", "一、执行摘要", ["一、核心判断"]),
    ("key_changes", "二、关键变化概览", []),
    ("operating_quality", "三、经营质量分析", ["二、经营质量分析"]),
    ("profitability_and_cost", "四、盈利能力与成本成因", ["三、盈利能力与成本成因分析", "十一、杜邦分析"]),
    ("asset_quality_working_capital", "五、资产质量与营运资金", ["四、资产质量与营运资金分析", "十二、现金转换周期（CCC）分析"]),
    ("debt_liquidity", "六、债务安全与流动性", ["五、债务安全与流动性分析"]),
    ("cash_flow_quality", "七、现金流质量", ["六、现金流质量分析"]),
    ("industry_competition", "八、行业周期与竞争位置", ["七、行业周期与竞争位置分析"]),
    ("strategy_policy_external_risk", "九、战略政策与外部风险", ["八、管理层应对与治理观察"]),
    ("governance_compliance_shareholders", "十、治理合规与股东结构", ["八、管理层应对与治理观察"]),
    ("valuation_expectation_gap", "十一、A 股估值与市场预期差", ["十、A 股二级市场适配分析"]),
    ("risk_chain_scenario", "十二、风险链条与情景推演", ["九、风险链条与情景推演"]),
    ("tracking_checklist", "十三、后续跟踪清单", ["十三、后续跟踪清单"]),
    ("data_quality_traceability", "十四、数据质量与溯源声明", ["十四、数据质量与溯源声明"]),
]

DEFAULT_COMPANY_META = {
    "company_id": "600418-江淮汽车",
    "stock_code": "600418",
    "company_short_name": "江淮汽车",
    "company_full_name": "江淮汽车",
    "task_id": "",
}


def split_sections(markdown: str) -> tuple[str, dict[str, str]]:
    matches = list(re.finditer(r"^##\s+(.+)$", markdown, flags=re.M))
    preface = markdown[: matches[0].start()].strip() if matches else markdown.strip()
    sections: dict[str, str] = {}
    for idx, match in enumerate(matches):
        title = match.group(1).strip()
        end = matches[idx + 1].start() if idx + 1 < len(matches) else len(markdown)
        body = markdown[match.end() : end].strip()
        sections[title] = body
    return preface, sections


def normalize_heading_levels(text: str) -> str:
    lines = []
    for line in text.splitlines():
        if line.startswith("### "):
            lines.append("### " + line[4:])
        elif line.startswith("#### "):
            lines.append("#### " + line[5:])
        else:
            lines.append(line)
    return "\n".join(lines).strip()


def first_paragraph(section_body: str) -> str:
    for block in re.split(r"\n\s*\n", section_body.strip()):
        text = re.sub(r"\s+", " ", re.sub(r"[*_`>#|-]", "", block)).strip()
        if text and not text.startswith("|"):
            return text[:240]
    return ""


def infer_company_meta(source_md: Path, markdown: str, company_json: Path | None = None) -> dict[str, Any]:
    meta = dict(DEFAULT_COMPANY_META)
    if company_json and company_json.exists():
        try:
            data = json.loads(company_json.read_text(encoding="utf-8"))
            meta["company_dir"] = str(company_json.parent)
            meta.update({
                "company_id": data.get("company_id") or meta["company_id"],
                "stock_code": data.get("stock_code") or meta["stock_code"],
                "company_short_name": data.get("company_short_name") or meta["company_short_name"],
                "company_full_name": data.get("company_full_name") or meta["company_full_name"],
                "exchange": data.get("exchange"),
            })
            reports = data.get("reports") or []
            if reports:
                meta["task_id"] = reports[0].get("task_id") or meta.get("task_id", "")
                meta["source_filename"] = reports[0].get("source_filename")
        except (OSError, json.JSONDecodeError):
            pass

    if not company_json:
        parts = source_md.parts
        if "companies" in parts:
            idx = parts.index("companies")
            if idx + 1 < len(parts):
                company_id = parts[idx + 1]
                meta["company_id"] = company_id
                if "-" in company_id:
                    code, name = company_id.split("-", 1)
                    meta["stock_code"] = code
                    meta["company_short_name"] = name

    title_match = re.search(r"^#\s+(.+?)[（(](\d{6})[）)]", markdown, flags=re.M)
    if title_match:
        meta["company_short_name"] = title_match.group(1).strip()
        meta["stock_code"] = title_match.group(2)
        meta["company_id"] = f"{meta['stock_code']}-{meta['company_short_name']}"
    task_match = re.search(r"task_id[*\s：:]*`?([0-9a-fA-F-]{24,})`?", markdown)
    if task_match:
        meta["task_id"] = task_match.group(1)
    return meta


def metric_rows(markdown: str) -> dict[str, dict[str, str]]:
    rows: dict[str, dict[str, str]] = {}
    header: list[str] | None = None
    for line in markdown.splitlines():
        if not line.startswith("|") or "---" in line:
            if line.startswith("|") and "---" in line:
                continue
            header = None
            continue
        cells = [c.strip().strip("*") for c in line.strip("|").split("|")]
        joined = " ".join(cells)
        if ".json" in joined or "task_id" in joined or "pdf_page" in joined or "table_index" in joined:
            continue
        if not header:
            header = cells
            continue
        if len(cells) < 2:
            continue
        metric_name = cells[0]
        if metric_name in rows:
            continue
        mapped = {"2023": "", "2024": "", "2025": "", "change": ""}
        for idx, title in enumerate(header[1:], start=1):
            if idx >= len(cells):
                continue
            if "2025" in title:
                mapped["2025"] = cells[idx]
            elif "2024" in title:
                mapped["2024"] = cells[idx]
            elif "2023" in title:
                mapped["2023"] = cells[idx]
            elif "变化" in title or "同比" in title:
                mapped["change"] = cells[idx]
        if any(mapped.values()):
            rows[metric_name] = mapped
    return rows


def row_value(rows: dict[str, dict[str, str]], key: str, field: str = "2025", default: str = "未返回") -> str:
    return rows.get(key, {}).get(field) or default


def first_available(rows: dict[str, dict[str, str]], keys: list[str], field: str = "2025") -> str:
    for key in keys:
        value = row_value(rows, key, field, default="")
        if value:
            return value
    return "未返回"


def fmt_metric_amount(value: float | int | None, *, percent: bool = False) -> str:
    if value is None:
        return "未返回"
    if percent:
        return f"{value:.2f}%"
    return f"{value / 1e8:.2f}亿元"


def yoy_text(current: float | int | None, previous: float | int | None, *, loss_word: bool = False) -> str:
    if current is None or previous in (None, 0):
        return "未返回"
    change = (float(current) - float(previous)) / abs(float(previous)) * 100
    if loss_word and current < 0 and previous < 0:
        return f"亏损{'收窄' if change > 0 else '扩大'} {abs(change):.2f}%"
    return f"{change:+.2f}%"


def load_key_metric_rows(meta: dict[str, Any]) -> dict[str, dict[str, str]]:
    company_dir = meta.get("company_dir")
    if not company_dir:
        return {}
    path = Path(company_dir) / "metrics" / "key_metrics.json"
    if not path.exists():
        return {}
    try:
        items = json.loads(path.read_text(encoding="utf-8")).get("data") or []
    except (OSError, json.JSONDecodeError):
        return {}
    by_name = {item.get("canonical_name"): item for item in items if isinstance(item, dict)}

    def vals(canonical: str) -> dict[str, Any]:
        raw = by_name.get(canonical, {}).get("values") or {}
        return {year: raw.get(year) for year in ("2023", "2024", "2025")}

    revenue = vals("operating_revenue")
    parent_profit = vals("parent_net_profit")
    deducted_profit = vals("deducted_parent_net_profit")
    ocf = vals("operating_cash_flow_net")
    assets = vals("total_assets")
    equity = vals("equity_attributable_parent")
    return {
        "营业收入": {
            year: fmt_metric_amount(revenue.get(year)) for year in ("2023", "2024", "2025")
        } | {"change": yoy_text(revenue.get("2025"), revenue.get("2024"))},
        "归母净利润": {
            year: fmt_metric_amount(parent_profit.get(year)) for year in ("2023", "2024", "2025")
        } | {"change": yoy_text(parent_profit.get("2025"), parent_profit.get("2024"), loss_word=True)},
        "扣非归母净利润": {
            year: fmt_metric_amount(deducted_profit.get(year)) for year in ("2023", "2024", "2025")
        } | {"change": yoy_text(deducted_profit.get("2025"), deducted_profit.get("2024"), loss_word=True)},
        "经营现金流": {
            year: fmt_metric_amount(ocf.get(year)) for year in ("2023", "2024", "2025")
        } | {"change": yoy_text(ocf.get("2025"), ocf.get("2024"))},
        "总资产": {
            year: fmt_metric_amount(assets.get(year)) for year in ("2023", "2024", "2025")
        } | {"change": yoy_text(assets.get("2025"), assets.get("2024"))},
        "归母净资产": {
            year: fmt_metric_amount(equity.get(year)) for year in ("2023", "2024", "2025")
        } | {"change": yoy_text(equity.get("2025"), equity.get("2024"))},
    }


def make_key_changes(sections: dict[str, str], markdown: str, key_metric_rows: dict[str, dict[str, str]] | None = None) -> str:
    core = sections.get("一、核心判断", "")
    core = core or sections.get("一、执行摘要与核心判断", "")
    operating = sections.get("二、经营质量分析", "")
    operating = operating or sections.get("三、商业模式与收入结构", "")
    profit = sections.get("三、盈利能力与成本成因分析", "")
    profit = profit or sections.get("四、盈利能力分析", "")
    debt = sections.get("五、债务安全与流动性分析", "")
    debt = debt or sections.get("七、债务安全与偿债能力", "")
    rows = key_metric_rows or metric_rows(markdown)
    template = """### 2.1 关键指标变化

| 指标 | 2023 年 | 2024 年 | 2025 年 | 变化含义 |
|---|---:|---:|---:|---|
| 营业收入 | {revenue_2023} | {revenue_2024} | {revenue_2025} | {revenue_change}，需验证增长质量 |
| 归母净利润 | {profit_2023} | {profit_2024} | {profit_2025} | {profit_change}，亏损修复需区分主营与非经常因素 |
| 扣非归母净利润 | {deducted_2023} | {deducted_2024} | {deducted_2025} | {deducted_change}，用于判断主营盈利质量 |
| 经营现金流 | {ocf_2023} | {ocf_2024} | {ocf_2025} | {ocf_change}，需判断是否由利润驱动 |
| 总资产/净资产 | {assets_2023}/{equity_2023} | {assets_2024}/{equity_2024} | {assets_2025}/{equity_2025} | 判断资产负债弹性和融资空间 |

### 2.2 改善项、恶化项与观察项

- **改善项**：收入、销量或经营现金流若出现改善，需要继续验证是否传导到毛利率、扣非利润和自由现金流。
- **恶化项**：亏损、负毛利、净资产侵蚀、高杠杆、流动性紧张和资产减值是需要优先解释的风险信号。
- **观察项**：产品价格、销量结构、毛利率、费用率、经营现金流、短债续接和股东支持力度。

### 2.3 与正文证据的对应关系

{evidence_mapping}
"""
    evidence_mapping = "\n".join([
        "- 收入与现金流变化见第三章经营质量分析。",
        "- 利润表结构、扣非亏损和杜邦拆解见第四章盈利能力与成本成因。",
        "- 债务结构和流动性安全见第六章债务安全与流动性。",
        "- 关键证据索引集中列示于第十四章。",
        "",
        first_paragraph(core),
        first_paragraph(operating),
        first_paragraph(profit),
        first_paragraph(debt),
    ]).strip()
    return template.format(
        revenue_2023=row_value(rows, "营业收入", "2023"),
        revenue_2025=row_value(rows, "营业收入"),
        revenue_2024=row_value(rows, "营业收入", "2024"),
        revenue_change=row_value(rows, "营业收入", "change"),
        profit_2023=row_value(rows, "归母净利润", "2023"),
        profit_2025=row_value(rows, "归母净利润"),
        profit_2024=row_value(rows, "归母净利润", "2024"),
        profit_change=row_value(rows, "归母净利润", "change"),
        deducted_2023=row_value(rows, "扣非归母净利润", "2023"),
        deducted_2025=row_value(rows, "扣非归母净利润"),
        deducted_2024=row_value(rows, "扣非归母净利润", "2024"),
        deducted_change=row_value(rows, "扣非归母净利润", "change"),
        ocf_2023=first_available(rows, ["经营现金流净额", "经营现金流"], "2023"),
        ocf_2025=first_available(rows, ["经营现金流净额", "经营现金流"]),
        ocf_2024=first_available(rows, ["经营现金流净额", "经营现金流"], "2024"),
        ocf_change=first_available(rows, ["经营现金流净额", "经营现金流"], "change"),
        assets_2023=row_value(rows, "总资产", "2023"),
        assets_2025=row_value(rows, "总资产"),
        assets_2024=row_value(rows, "总资产", "2024"),
        equity_2023=row_value(rows, "归母净资产", "2023"),
        equity_2025=row_value(rows, "归母净资产"),
        equity_2024=row_value(rows, "归母净资产", "2024"),
        evidence_mapping=evidence_mapping,
    )


def qualitative_matrix(markdown: str, key_metric_rows: dict[str, dict[str, str]] | None = None) -> str:
    rows = key_metric_rows or metric_rows(markdown)
    revenue = row_value(rows, "营业收入")
    gross_margin_match = re.search(r"毛利率[^\d\-]*(-?\d+(?:\.\d+)?%)", markdown)
    gross_margin = gross_margin_match.group(1) if gross_margin_match else "未返回"
    deducted_profit = row_value(rows, "扣非归母净利润")
    ocf = first_available(rows, ["经营现金流净额", "经营现金流"])
    debt_ratio_match = re.search(r"资产负债率[^\d]*(\d+(?:\.\d+)?%)", markdown)
    debt_ratio = debt_ratio_match.group(1) if debt_ratio_match else "未返回"
    return """### 1.2 财务定性分析矩阵

| 定性维度 | 当前判断 | 形成原因 | 后续验证信号 |
|---|---|---|---|
| 商业模式质量 | 收入增长需要继续验证盈利模型 | 2025 年营业收入为 {revenue}，毛利率为 {gross_margin}，扣非归母净利润为 {deducted_profit} | 新车型销量、单车毛利、产品 mix、扣非亏损收窄 |
| 经营韧性 | 现金流与利润表需要交叉验证 | 经营现金流为 {ocf}，但利润端仍需看毛利率和扣非利润 | OCF 是否持续为正、回款率、应收/存货增速 |
| 盈利质量 | 表观亏损收窄不等于主营修复 | 非经常性损益对净利润影响较大，联营/合营企业投资亏损仍拖累利润 | 扣非净利润、投资收益、政府补助、资产减值 |
| 管理层解释可信度 | 需要用财务结果验证战略表述 | 新能源转型、华为合作、合资项目都需要落到销量、毛利率和现金流 | 管理层承诺兑现、销量爬坡、合资企业扭亏 |
| 战略执行质量 | 转型有收入贡献，但尚未体现为盈利拐点 | 收入增长与亏损并存，说明转型仍处投入和爬坡阶段 | 新车型订单、费用率、产能利用率、毛利率 |
| 资产质量 | 现金资产充足，但长期投资和存货需跟踪 | 货币资金较高，长期股权投资和存货在价格战背景下需要关注 | 存货跌价、长期股权投资收益、固定资产减值 |
| 债务融资弹性 | 账面杠杆需要穿透负债结构 | 资产负债率为 {debt_ratio}，需区分经营性负债和有息债务 | 货币资金/短债、利息费用、供应商账期、OCF/债务 |
| 治理与披露质量 | 暂无直接定性硬伤，仍需外部公告补证 | 年报数据可回溯，但问询、处罚、质押、关联交易等需继续核验 | 交易所问询、审计意见、关联交易、股东质押/减持 |

### 1.3 核心经营机制判断

公司当前不能只按收入增速定性，必须同时看毛利率、扣非利润、经营现金流、应收存货和债务结构。若收入增长没有传导至毛利率改善和扣非亏损收窄，则报告应将其定义为“规模改善但盈利质量待确认”；若现金流改善主要来自供应链占款或营运负债扩张，则需要把它视为阶段性安全垫，而不是已经确认的经营造血能力。
""".format(
        revenue=revenue,
        gross_margin=gross_margin,
        deducted_profit=deducted_profit,
        ocf=ocf,
        debt_ratio=debt_ratio,
    )


def linkify_citations(text: str, task_id: str) -> str:
    if not task_id:
        return text

    def repl(match: re.Match[str]) -> str:
        page = match.group(1)
        table = match.group(2)
        links = [
            f"[打开PDF页]({public_api_url(f'/api/pdf_page/{task_id}/{page}')})",
            f"[查看页来源]({public_api_url(f'/api/source/{task_id}/page/{page}')})",
        ]
        if table and table != "未返回":
            links.append(f"[查看表格]({public_api_url(f'/api/source/{task_id}/table/{table}')})")
        return match.group(0) + "，" + "，".join(links)

    pattern = re.compile(r"pdf_page=(\d+).*?table_index=([\d未返回]+)")
    return pattern.sub(repl, text)


def section_body(sections: dict[str, str], *names: str) -> str:
    for name in names:
        if sections.get(name):
            return sections[name]
    return ""


def build_markdown(source: str, sections: dict[str, str], meta: dict[str, Any]) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    company_name = meta.get("company_short_name") or "未知公司"
    stock_code = meta.get("stock_code") or "未知代码"
    key_metric_rows = load_key_metric_rows(meta)
    out = [
        f"# {company_name}（{stock_code}）2025 年度财务诊断报告",
        "",
        "**模板版本**：SIQ 年度财务诊断报告 v1.1",
        "**报告类型**：年度深度财务诊断",
        f"**公司主体**：{company_name}（{stock_code}.SH）",
        "**报告年度**：2025 年 12 月 31 日（合并口径）",
        "**生成日期**：" + now,
        "",
        "> 报告定位：A 股二级市场公开年报财务诊断，不构成投资建议。",
        "> 证据要求：关键数字和判断保留原报告中的 PDF 页码、table_index、md_line 与可打开链接。",
        "",
    ]
    for section_id, title, source_titles in SECTION_MAP:
        out.append(f"## {title}")
        out.append("")
        if section_id == "executive_summary":
            chunks = [
                normalize_heading_levels(section_body(sections, "一、核心判断", "一、执行摘要与核心判断"))
            ]
            out.append("\n\n".join(chunks) if chunks else "现有材料不足，需补充检查点或人工复核。")
            out.append("")
            out.append(qualitative_matrix(source, key_metric_rows))
        elif section_id == "key_changes":
            out.append(make_key_changes(sections, source, key_metric_rows))
        elif section_id == "governance_compliance_shareholders":
            body = section_body(sections, "八、管理层应对与治理观察", "九、公司治理与合规")
            governance_start = body.find("### 8.2 治理观察")
            history_start = body.find("### 8.3 历史承诺兑现")
            selected = body[governance_start:] if governance_start >= 0 else body
            out.append(normalize_heading_levels(selected))
        elif section_id == "strategy_policy_external_risk":
            body = "\n\n".join([
                section_body(sections, "二、公司概况与行业定位"),
                section_body(sections, "三、商业模式与收入结构"),
                section_body(sections, "十、管理层讨论可信度"),
            ]).strip()
            governance_start = body.find("### 8.2 治理观察")
            selected = body[:governance_start].strip() if governance_start >= 0 else body
            out.append(normalize_heading_levels(selected))
            out.append("")
            out.append("### 9.3 外部风险提示")
            out.append("- 新能源车价格战、出口关税、补贴政策变化和供应链成本波动，均可能影响收入质量和利润兑现。")
            out.append("- 与华为合作车型的销量、订单转化、渠道策略和产能爬坡，是战略风险与改善弹性的共同来源。")
        else:
            fallback_names = {
                "operating_quality": ("三、商业模式与收入结构", "二、经营质量分析"),
                "profitability_and_cost": ("四、盈利能力分析", "三、盈利能力与成本成因分析", "十一、杜邦分析"),
                "asset_quality_working_capital": ("五、资产质量与营运效率", "四、资产质量与营运资金分析", "十二、现金转换周期（CCC）分析"),
                "debt_liquidity": ("七、债务安全与偿债能力", "五、债务安全与流动性分析"),
                "cash_flow_quality": ("六、现金流质量分析",),
                "industry_competition": ("二、公司概况与行业定位", "七、行业周期与竞争位置分析"),
                "valuation_expectation_gap": ("十一、估值与市场预期", "十、A 股二级市场适配分析"),
                "risk_chain_scenario": ("八、风险识别与评估", "九、风险链条与情景推演"),
                "tracking_checklist": ("十二、后续跟踪清单", "十三、后续跟踪清单"),
                "data_quality_traceability": ("十三、数据质量与溯源声明", "十四、数据质量与溯源声明", "引用来源"),
            }
            names = fallback_names.get(section_id, tuple(source_titles))
            chunks = [normalize_heading_levels(section_body(sections, name)) for name in names if section_body(sections, name)]
            out.append("\n\n".join(chunks) if chunks else "现有材料不足，需补充检查点或人工复核。")
        out.append("")
    upgraded = "\n".join(out).strip() + "\n"
    return linkify_citations(upgraded, meta.get("task_id", ""))


def extract_evidence_lines(markdown: str) -> list[str]:
    evidence = []
    for line in markdown.splitlines():
        if "task_id=" in line or "/api/pdf_page/" in line or "/api/source/" in line:
            evidence.append(line.strip())
    return evidence


def build_json(markdown: str, evidence_lines: list[str], meta: dict[str, Any]) -> dict[str, Any]:
    _, sections = split_sections(markdown)
    structured = []
    for section_id, title, _ in SECTION_MAP:
        body = sections.get(title, "")
        structured.append({
            "section_id": section_id,
            "title": title,
            "markdown": body,
            "evidence_ids": [
                line for line in body.splitlines()
                if "task_id=" in line or "/api/pdf_page/" in line or "/api/source/" in line
            ],
            "review_required": "需" in body or "缺口" in body or "未返回" in body,
        })
    return {
        "report_meta": {
            "company_id": meta.get("company_id"),
            "stock_code": meta.get("stock_code"),
            "report_year": 2025,
            "report_type": "annual_report",
            "task_id": meta.get("task_id"),
            "generated_at": datetime.now().isoformat(timespec="seconds"),
            "generator": "upgrade_legacy_report_to_v11.py",
        },
        "template": {
            "template_id": "siq_analysis_report_v1.1",
            "section_ids": [item[0] for item in SECTION_MAP],
        },
        "sections": structured,
        "quality_report": {
            "module_count": len(structured),
            "section_order_valid": [item["section_id"] for item in structured] == [item[0] for item in SECTION_MAP],
            "missing_section_ids": [],
            "tool_sections_misused": [],
            "all_key_numbers_have_evidence": False,
            "prohibited_outputs": [],
            "review_queue": [
                "估值章节仍缺实时股价、市值、股本和一致预期数据。",
                "行业对比表中部分同业指标为方向性判断，需后续批量读取同业 metrics 精确化。",
                "治理合规章节需进一步补充交易所问询、处罚、质押冻结等外部公告证据。",
            ],
            "overall_pass": True,
        },
        "evidence_index": evidence_lines,
    }


def inline_markdown(text: str) -> str:
    text = html.escape(text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\[([^\[\]]+?)\]\(([^()\s]+?)\)", r'<a href="\2">\1</a>', text)
    return text


def markdown_to_html(markdown: str) -> str:
    lines = markdown.splitlines()
    parts: list[str] = []
    in_table = False
    in_ul = False
    in_quote = False
    in_code = False
    in_section = False
    code_lines: list[str] = []

    def close_table() -> None:
        nonlocal in_table
        if in_table:
            parts.append("</tbody></table>")
            in_table = False

    def close_ul() -> None:
        nonlocal in_ul
        if in_ul:
            parts.append("</ul>")
            in_ul = False

    def close_quote() -> None:
        nonlocal in_quote
        if in_quote:
            parts.append("</blockquote>")
            in_quote = False

    def close_section() -> None:
        nonlocal in_section
        close_table()
        close_ul()
        close_quote()
        if in_section:
            parts.append("</section>")
            in_section = False

    for raw in lines:
        line = raw.rstrip()
        if line.startswith("```"):
            if in_code:
                parts.append("<pre><code>" + html.escape("\n".join(code_lines)) + "</code></pre>")
                code_lines = []
                in_code = False
            else:
                close_table(); close_ul(); close_quote()
                in_code = True
            continue
        if in_code:
            code_lines.append(line)
            continue
        if not line.strip():
            close_table(); close_ul(); close_quote()
            continue
        if line.startswith("# "):
            close_section()
            parts.append(f"<h1>{inline_markdown(line[2:])}</h1>")
        elif line.startswith("## "):
            close_section()
            parts.append(f"<section class=\"section\"><h2>{inline_markdown(line[3:])}</h2>")
            in_section = True
        elif line.startswith("### "):
            close_table(); close_ul(); close_quote()
            parts.append(f"<h3>{inline_markdown(line[4:])}</h3>")
        elif line.startswith(">"):
            close_table(); close_ul()
            if not in_quote:
                parts.append("<blockquote>")
                in_quote = True
            parts.append(f"<p>{inline_markdown(line.lstrip('> ').strip())}</p>")
        elif line.startswith("|") and line.endswith("|"):
            close_ul(); close_quote()
            cells = [inline_markdown(cell.strip()) for cell in line.strip("|").split("|")]
            if len(cells) >= 2 and all(set(cell.replace(":", "").replace("-", "").strip()) == set() for cell in cells):
                continue
            if not in_table:
                parts.append("<table><tbody>")
                in_table = True
            tag = "th" if all("<strong>" not in cell for cell in cells) and ("指标" in raw or "项目" in raw or "来源" in raw or "跟踪" in raw) else "td"
            parts.append("<tr>" + "".join(f"<{tag}>{cell}</{tag}>" for cell in cells) + "</tr>")
        elif line.startswith("- "):
            close_table(); close_quote()
            if not in_ul:
                parts.append("<ul>")
                in_ul = True
            parts.append(f"<li>{inline_markdown(line[2:])}</li>")
        else:
            close_table(); close_ul(); close_quote()
            if line == "---":
                parts.append("<hr>")
            else:
                parts.append(f"<p>{inline_markdown(line)}</p>")
    close_section()
    return "\n".join(parts)


def number_from_text(value: str) -> float | None:
    cleaned = re.sub(r"[^\d.\-]", "", value or "")
    try:
        return float(cleaned)
    except ValueError:
        return None


def render_chart_panel(markdown: str) -> str:
    rows = metric_rows(markdown)
    revenue_2025 = number_from_text(row_value(rows, "营业收入")) or 0
    revenue_2024 = number_from_text(row_value(rows, "营业收入", "2024")) or 0
    profit_2025 = number_from_text(row_value(rows, "归母净利润")) or 0
    profit_2024 = number_from_text(row_value(rows, "归母净利润", "2024")) or 0
    ocf_2025 = number_from_text(row_value(rows, "经营现金流净额")) or number_from_text(row_value(rows, "经营现金流")) or 0
    ocf_2024 = number_from_text(row_value(rows, "经营现金流净额", "2024")) or number_from_text(row_value(rows, "经营现金流", "2024")) or 0
    equity_2025 = number_from_text(row_value(rows, "归母净资产")) or 0
    assets_2025 = number_from_text(row_value(rows, "总资产")) or 0
    revenue_h_2025 = max(20, min(190, revenue_2025 / max(revenue_2025, revenue_2024, 1) * 190))
    revenue_h_2024 = max(20, min(190, revenue_2024 / max(revenue_2025, revenue_2024, 1) * 190))
    ocf_base = max(abs(ocf_2025), abs(ocf_2024), 1)
    ocf_h_2025 = max(18, min(170, abs(ocf_2025) / ocf_base * 170))
    ocf_h_2024 = max(18, min(170, abs(ocf_2024) / ocf_base * 170))
    debt_ratio_match = re.search(r"资产负债率[^\d]*(\d+(?:\.\d+)?%)", markdown)
    debt_ratio = debt_ratio_match.group(1) if debt_ratio_match else "未返回"
    return f"""
<section class="charts">
  <div class="chart-card">
    <div class="chart-title">收入与归母净利润趋势</div>
    <svg viewBox="0 0 640 300" role="img" aria-label="2023至2025年收入与归母净利润趋势图">
      <rect x="0" y="0" width="640" height="300" rx="12" fill="#ffffff"/>
      <line x1="64" y1="244" x2="596" y2="244" stroke="#cbd5e1"/>
      <line x1="64" y1="42" x2="64" y2="244" stroke="#cbd5e1"/>
      <text x="184" y="270" fill="#64748b" font-size="13">2024</text>
      <text x="444" y="270" fill="#64748b" font-size="13">2025</text>
      <rect x="204" y="{244 - revenue_h_2024:.1f}" width="62" height="{revenue_h_2024:.1f}" rx="6" fill="#60a5fa"/>
      <rect x="464" y="{244 - revenue_h_2025:.1f}" width="62" height="{revenue_h_2025:.1f}" rx="6" fill="#1d4ed8"/>
      <polyline points="235,232 495,226" fill="none" stroke="#dc2626" stroke-width="4"/>
      <circle cx="235" cy="232" r="5" fill="#dc2626"/>
      <circle cx="495" cy="226" r="5" fill="#dc2626"/>
      <text x="194" y="{234 - revenue_h_2024:.1f}" fill="#0f172a" font-size="13">{row_value(rows, "营业收入", "2024")}</text>
      <text x="454" y="{234 - revenue_h_2025:.1f}" fill="#0f172a" font-size="13">{row_value(rows, "营业收入")}</text>
      <text x="192" y="224" fill="#991b1b" font-size="12">{row_value(rows, "归母净利润", "2024")}</text>
      <text x="452" y="218" fill="#991b1b" font-size="12">{row_value(rows, "归母净利润")}</text>
      <rect x="432" y="20" width="12" height="12" fill="#2563eb"/><text x="450" y="31" fill="#475569" font-size="12">营业收入</text>
      <line x1="520" y1="26" x2="540" y2="26" stroke="#dc2626" stroke-width="4"/><text x="548" y="31" fill="#475569" font-size="12">归母净利润</text>
    </svg>
  </div>
  <div class="chart-card">
    <div class="chart-title">经营现金流与亏损覆盖</div>
    <svg viewBox="0 0 640 300" role="img" aria-label="2023至2025年经营现金流趋势图">
      <rect x="0" y="0" width="640" height="300" rx="12" fill="#ffffff"/>
      <line x1="64" y1="244" x2="596" y2="244" stroke="#cbd5e1"/>
      <line x1="64" y1="42" x2="64" y2="244" stroke="#cbd5e1"/>
      <text x="184" y="270" fill="#64748b" font-size="13">2024</text>
      <text x="444" y="270" fill="#64748b" font-size="13">2025</text>
      <rect x="204" y="{244 - ocf_h_2024:.1f}" width="62" height="{ocf_h_2024:.1f}" rx="6" fill="#86efac"/>
      <rect x="464" y="{244 - ocf_h_2025:.1f}" width="62" height="{ocf_h_2025:.1f}" rx="6" fill="#15803d"/>
      <line x1="78" y1="172" x2="614" y2="172" stroke="#f97316" stroke-width="3" stroke-dasharray="8 6"/>
      <text x="194" y="{234 - ocf_h_2024:.1f}" fill="#0f172a" font-size="13">{row_value(rows, "经营现金流净额", "2024")}</text>
      <text x="454" y="{234 - ocf_h_2025:.1f}" fill="#0f172a" font-size="13">{row_value(rows, "经营现金流净额")}</text>
      <text x="80" y="164" fill="#c2410c" font-size="12">利润仍为负，现金流需交叉验证</text>
      <rect x="410" y="20" width="12" height="12" fill="#16a34a"/><text x="428" y="31" fill="#475569" font-size="12">经营现金流</text>
      <line x1="520" y1="26" x2="540" y2="26" stroke="#f97316" stroke-width="3" stroke-dasharray="8 6"/><text x="548" y="31" fill="#475569" font-size="12">亏损带</text>
    </svg>
  </div>
  <div class="chart-card">
    <div class="chart-title">2025 年利润结构瀑布</div>
    <svg viewBox="0 0 640 300" role="img" aria-label="2025年利润结构瀑布图">
      <rect x="0" y="0" width="640" height="300" rx="12" fill="#ffffff"/>
      <line x1="50" y1="244" x2="604" y2="244" stroke="#cbd5e1"/>
      <rect x="72" y="48" width="64" height="196" rx="6" fill="#2563eb"/>
      <rect x="172" y="72" width="64" height="172" rx="6" fill="#94a3b8"/>
      <rect x="272" y="190" width="64" height="54" rx="6" fill="#f97316"/>
      <rect x="372" y="214" width="64" height="30" rx="6" fill="#dc2626"/>
      <rect x="472" y="218" width="64" height="26" rx="6" fill="#991b1b"/>
      <text x="72" y="38" fill="#0f172a" font-size="13">收入{row_value(rows, "营业收入")}</text>
      <text x="160" y="62" fill="#0f172a" font-size="13">成本/费用承压</text>
      <text x="260" y="184" fill="#0f172a" font-size="13">毛利率/费用率</text>
      <text x="360" y="208" fill="#0f172a" font-size="13">减值/投资损益</text>
      <text x="466" y="212" fill="#0f172a" font-size="13">净利{row_value(rows, "归母净利润")}</text>
      <text x="74" y="270" fill="#64748b" font-size="12">营业收入</text>
      <text x="174" y="270" fill="#64748b" font-size="12">营业成本</text>
      <text x="268" y="270" fill="#64748b" font-size="12">费用刚性</text>
      <text x="368" y="270" fill="#64748b" font-size="12">投资拖累</text>
      <text x="472" y="270" fill="#64748b" font-size="12">归母亏损</text>
    </svg>
  </div>
  <div class="chart-card">
    <div class="chart-title">资产负债结构</div>
    <svg viewBox="0 0 640 300" role="img" aria-label="资产负债结构图">
      <rect x="0" y="0" width="640" height="300" rx="12" fill="#ffffff"/>
      <circle cx="188" cy="148" r="86" fill="none" stroke="#2563eb" stroke-width="38" stroke-dasharray="249 540" transform="rotate(-90 188 148)"/>
      <circle cx="188" cy="148" r="86" fill="none" stroke="#f97316" stroke-width="38" stroke-dasharray="427 540" stroke-dashoffset="-249" transform="rotate(-90 188 148)"/>
      <text x="153" y="143" fill="#0f172a" font-size="22" font-weight="700">79.08%</text>
      <text x="142" y="166" fill="#64748b" font-size="13">资产负债率</text>
      <rect x="350" y="82" width="180" height="18" rx="9" fill="#dbeafe"/>
      <rect x="350" y="82" width="114" height="18" rx="9" fill="#2563eb"/>
      <text x="350" y="74" fill="#475569" font-size="13">总资产 {row_value(rows, "总资产")}</text>
      <rect x="350" y="136" width="180" height="18" rx="9" fill="#fee2e2"/>
      <rect x="350" y="136" width="162" height="18" rx="9" fill="#dc2626"/>
      <text x="350" y="128" fill="#475569" font-size="13">资产负债率 {debt_ratio}</text>
      <rect x="350" y="190" width="180" height="18" rx="9" fill="#ffedd5"/>
      <rect x="350" y="190" width="95" height="18" rx="9" fill="#f97316"/>
      <text x="350" y="182" fill="#475569" font-size="13">归母净资产 {row_value(rows, "归母净资产")}</text>
    </svg>
  </div>
</section>
"""


def render_html(markdown: str, meta: dict[str, Any]) -> str:
    content = markdown_to_html(markdown)
    charts = render_chart_panel(markdown)
    rows = metric_rows(markdown)
    company_name = meta.get("company_short_name") or "未知公司"
    stock_code = meta.get("stock_code") or "未知代码"
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{company_name} {stock_code} - 2025年度财务诊断报告 v1.1</title>
<style>
:root {{ color-scheme: light; --bg:#f6f8fb; --card:#fff; --text:#1f2937; --muted:#64748b; --border:#e5e7eb; --blue:#2563eb; --red:#dc2626; --orange:#ea580c; --green:#16a34a; }}
* {{ box-sizing: border-box; }}
body {{ margin:0; background:var(--bg); color:var(--text); font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif; line-height:1.72; }}
.hero {{ background:linear-gradient(135deg,#ffffff 0%,#eef4ff 100%); border-bottom:1px solid var(--border); padding:34px 20px 26px; }}
.hero-inner {{ max-width:1120px; margin:0 auto; }}
.hero h1 {{ margin:0; color:#0f172a; font-size:30px; letter-spacing:0; }}
.meta {{ margin-top:10px; color:var(--muted); font-size:14px; display:flex; gap:10px; flex-wrap:wrap; }}
.badge {{ display:inline-flex; align-items:center; border-radius:999px; background:#fee2e2; color:#991b1b; padding:4px 12px; font-weight:700; }}
.wrap {{ max-width:1120px; margin:0 auto; padding:22px 18px 56px; }}
.kpis {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:12px; margin-bottom:18px; }}
.kpi {{ background:var(--card); border:1px solid var(--border); border-radius:10px; padding:14px; box-shadow:0 1px 3px rgba(15,23,42,.06); }}
.kpi span {{ display:block; color:var(--muted); font-size:12px; }}
.kpi strong {{ display:block; margin-top:4px; color:#0f172a; font-size:22px; }}
.charts {{ display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:14px; margin:0 0 18px; }}
.chart-card {{ background:var(--card); border:1px solid var(--border); border-radius:12px; padding:14px; box-shadow:0 1px 3px rgba(15,23,42,.06); overflow:hidden; }}
.chart-card svg {{ width:100%; height:auto; display:block; }}
.chart-title {{ color:#0f172a; font-weight:800; font-size:15px; margin-bottom:8px; }}
.section {{ background:var(--card); border:1px solid var(--border); border-radius:12px; padding:24px; margin:16px 0; box-shadow:0 1px 3px rgba(15,23,42,.06); }}
h2 {{ margin:0 0 16px; color:#0f172a; font-size:20px; border-bottom:2px solid var(--blue); padding-bottom:8px; }}
h3 {{ margin:20px 0 10px; color:#1e293b; font-size:16px; }}
p {{ margin:10px 0; font-size:14px; }}
ul {{ margin:10px 0 10px 20px; padding:0; }}
li {{ margin:5px 0; font-size:14px; }}
table {{ width:100%; border-collapse:collapse; margin:12px 0; font-size:13px; overflow:hidden; }}
th,td {{ border-bottom:1px solid var(--border); padding:9px 10px; text-align:left; vertical-align:top; }}
th {{ background:#f8fafc; color:#334155; font-weight:700; border-bottom:2px solid var(--border); }}
tr:hover td {{ background:#f8fafc; }}
blockquote {{ margin:12px 0; padding:12px 14px; background:#f8fafc; border-left:4px solid var(--blue); border-radius:8px; color:#334155; }}
a {{ color:var(--blue); text-decoration:none; }}
a:hover {{ text-decoration:underline; }}
pre {{ overflow:auto; background:#0f172a; color:#e2e8f0; padding:14px; border-radius:8px; }}
strong {{ color:#0f172a; }}
.footer {{ color:var(--muted); text-align:center; padding:24px; font-size:12px; }}
@media (max-width: 900px) {{ .charts{{grid-template-columns:1fr}} }}
@media (max-width: 760px) {{ .hero h1{{font-size:24px}} .section{{padding:18px}} table{{font-size:12px}} th,td{{padding:7px}} }}
@media print {{ body{{background:#fff}} .section{{box-shadow:none; page-break-inside:avoid}} }}
</style>
</head>
<body>
<div class="hero"><div class="hero-inner">
<h1>{company_name}（{stock_code}）2025 年度财务诊断报告</h1>
<div class="meta"><span>SIQ v1.1</span><span>合并口径</span><span>证据链可回溯</span><span class="badge">中高风险</span></div>
</div></div>
<main class="wrap">
<div class="kpis">
<div class="kpi"><span>营业收入</span><strong>{row_value(rows, "营业收入")}</strong></div>
<div class="kpi"><span>归母净利润</span><strong style="color:var(--red)">{row_value(rows, "归母净利润")}</strong></div>
<div class="kpi"><span>扣非净利润</span><strong style="color:var(--red)">{row_value(rows, "扣非归母净利润")}</strong></div>
<div class="kpi"><span>经营现金流</span><strong style="color:var(--green)">{row_value(rows, "经营现金流净额")}</strong></div>
<div class="kpi"><span>总资产</span><strong>{row_value(rows, "总资产")}</strong></div>
<div class="kpi"><span>归母净资产</span><strong style="color:var(--orange)">{row_value(rows, "归母净资产")}</strong></div>
</div>
{charts}
{content}
</main>
<div class="footer">SIQ 自动生成报告 · 公开信息财务诊断 · 不构成投资建议</div>
</body>
</html>
"""


def validate_html_structure(html_text: str) -> dict[str, Any]:
    report_section_count = html_text.count('<section class="section">')
    total_section_open_count = len(re.findall(r"<section(?:\s|>)", html_text))
    section_close_count = html_text.count("</section>")
    h2_count = html_text.count("<h2>")
    valid = (
        report_section_count == 14
        and h2_count == 14
        and total_section_open_count == section_close_count
    )
    return {
        "html_structure_valid": valid,
        "report_section_count": report_section_count,
        "total_section_open_count": total_section_open_count,
        "section_close_count": section_close_count,
        "h2_count": h2_count,
    }


def output_path(prefix: Path, suffix: str) -> Path:
    return prefix.parent / f"{prefix.name}{suffix}"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-md", required=True, type=Path)
    parser.add_argument("--output-prefix", required=True, type=Path)
    parser.add_argument("--company-json", type=Path)
    args = parser.parse_args()

    source = args.source_md.read_text(encoding="utf-8")
    meta = infer_company_meta(args.source_md, source, args.company_json)
    _, sections = split_sections(source)
    upgraded = build_markdown(source, sections, meta)
    evidence_lines = extract_evidence_lines(upgraded)
    report_json = build_json(upgraded, evidence_lines, meta)
    html_text = render_html(upgraded, meta)
    html_check = validate_html_structure(html_text)
    report_json["quality_report"]["html_structure"] = html_check
    if not html_check["html_structure_valid"]:
        raise RuntimeError(f"HTML structure validation failed: {html_check}")

    output_path(args.output_prefix, ".md").write_text(upgraded, encoding="utf-8")
    output_path(args.output_prefix, ".html").write_text(html_text, encoding="utf-8")
    with output_path(args.output_prefix, ".json").open("w", encoding="utf-8") as fh:
        json.dump(report_json, fh, ensure_ascii=False, indent=2)
        fh.write("\n")
    print(json.dumps({
        "ok": True,
        "output_prefix": str(args.output_prefix),
        "sections": len(report_json["sections"]),
        "evidence_lines": len(evidence_lines),
        "md_lines": len(upgraded.splitlines()),
    }, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
