"""Attachment-facing facade for the Hermes agent runtime."""

from __future__ import annotations

from .agent_chat_runtime_impl import (
    _attachment_dicts,
    _attachment_metadata,
    _attachment_reference_context,
    _attachments_with_fresh_metadata,
    _display_message_with_attachments,
    _document_attachment_context,
    _document_attachment_dicts,
    _document_text_preview,
    _ensure_chatmessage_attachments_column,
    _image_attachment_data_url,
    _image_attachment_dicts,
    _message_attachments,
    _pdf_attachment_parse_dirs,
    _pdf_parse_is_terminal,
    _read_docx_text,
    _read_pdf_text_with_pdftotext,
    _resolve_image_model_name,
    _safe_chat_path,
    _safe_uploaded_path,
    _should_reuse_recent_attachments,
    _truncate_document_text,
    analyze_images_with_primary_model,
    chat_message_has_visible_payload,
    load_recent_session_attachments,
    wait_for_pdf_attachment_parses,
)

__all__ = [
    "_attachment_dicts",
    "_attachment_metadata",
    "_attachment_reference_context",
    "_attachments_with_fresh_metadata",
    "_display_message_with_attachments",
    "_document_attachment_context",
    "_document_attachment_dicts",
    "_document_text_preview",
    "_ensure_chatmessage_attachments_column",
    "_image_attachment_data_url",
    "_image_attachment_dicts",
    "_message_attachments",
    "_pdf_attachment_parse_dirs",
    "_pdf_parse_is_terminal",
    "_read_docx_text",
    "_read_pdf_text_with_pdftotext",
    "_resolve_image_model_name",
    "_safe_chat_path",
    "_safe_uploaded_path",
    "_should_reuse_recent_attachments",
    "_truncate_document_text",
    "analyze_images_with_primary_model",
    "chat_message_has_visible_payload",
    "load_recent_session_attachments",
    "wait_for_pdf_attachment_parses",
]
